### ISSUE TITLE
Error when using the mod

### ISSUE THREAD

**Issue by TheRealGorkiDood** [TheKillerey/Old-Summoners-Rift-V2#3]
I get the following error when running 
Old.Minions.Night.V1.0.0.by.TheKillereyXAryasdemise 
and
Old.Summoners.Rift.V2.Night.V1.0.1.by.TheKillerey

backtrace: 
  lol::io::Buffer::reserve:
    size_ = 0x0
    pos = 0x0
    count = 0x42636bb8
  lol::wad::Archive::write_to_file:
    path = ./profiles/Default Profile/DATA/FINAL/Maps/Shipping/Map12.wad.client
  lol::wad::Index::write_to_directory:
    this->name = 
    dir = ./profiles/Default Profile
  mod_mkoverlay:
    src = ./installed
    dst = ./profiles/Default Profile
    game = E:/Riot Games/League of Legends/Game
error: impl_reserve(endpos) -> unknown error
name: Run mod-tools
version: 2024-05-18-dc60dd1

**Comment by WonderNoob** [comment]
You don't have enough space on your hard drive. You're missing about 1GB of space.
You can check the RuneForge Discord's help-channel. The WIP-Chip bot there can help you with these errors if you get one again.
